subject: aj1
date: 20180312
ranges:
    lower: [154, 99, 70]
    upper: [255, 255, 255]

folderpath:
    calibration: '/mnt/data/Research/micontinuous/aj1_micontinuous/20180312/tracking/calibration/'
    tracking:    '/mnt/data/Research/micontinuous/aj1_micontinuous/20180312/tracking/'
    robot:       '/mnt/data/Research/micontinuous/aj1_micontinuous/20180312/robot/'

calibration: 
    file: '/mnt/data/Research/micontinuous/aj1_micontinuous/20180312/tracking/20180312_morning_calibration.bag'

# Constant definitions for calibration and tracking (not supposed to be changed)
    coordinates:
        points:
            - [450, 0, 0]           # P0
            - [0, 0, 0]             # P1
            - [150, 150, 0]         # P2
            - [238, 362, 0]         # P3
            - [150, 500, 0]         # P4
            - [0, 600, 0]           # P5
            - [450, 450, 0]         # P6
            - [450, 600, 0]         # P7
            - [662, 362, 0]         # P8
            - [750, 500, 0]         # P9
            - [900, 600, 0]         # P10
            - [900, 0, 0]           # P11
            - [750, 150, 0]         # P12
            - [450, 150, 0]         # P13
            - [450, 300, 0]         # P14
        training: [1, 2, 3, 5, 6, 8, 10, 11, 12, 14]
        testing:  [0, 4, 7, 9, 13]
        starting: 13
    
    camera:
        kinect2:
            matrix:
                - [1040.1843288568414,  0., 970.13113463795378]
                - [0., 1043.4786764992630, 586.69082331127413] 
                - [0.,                 0.,                 1.]
            distortion: [-0.10368441366207955, 0.14700034102120813, 
                          0.0094783197801610788, -0.0054333362938346818, 
                          -0.076421828610787820]
        kinect1:
            matrix:
                - [534.5677243503536, 0, 319.0661884802727]
                - [0, 533.3990166791197, 261.0306214954068] 
                - [0.,                 0.,                 1.]
            distortion: [0.2450541033705403, -0.3901175680464315, 
                         -0.002732452946342192, 0.009749225533570473, 0]


rostopics:
    video: '/kinect2/hd/image_color/compressed'
    tid:   '/rostid_cnbi2ros'
    tic:   '/rostic_cnbi2ros'
    odom:  '/odom'
